# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=~/.i3/blocks/$BLOCK_NAME
separator_block_width=15
markup=none

# Part 1

#[user]
#label=
#interval=once

[battery]
#label= 
interval=5

#[mail]
#label= P
# instance is the name of the script in ~/.local/bin to execute.
# edit that script to input credentials.
#instance=mail.pers
#interval=60

#[mail]
#label= W
# instance is the name of the script in ~/.local/bin to execute.
# edit that script to input credentials.
#instance=mail.work
#interval=60

[audio]
label=
interval=5

[microphone]
label=
interval=5

[cpu]
label= CPU
interval=2

[memory]
label= RAM
instance=mem;used
interval=30

[memory]
label= SWP
instance=swap;used
interval=30

[space]
label= /
instance=/;used
interval=30

#[space]
#label=  BOOT
#instance=/boot;used
#interval=30

[space]
label= ~/
instance=$HOME;used
interval=30

#[network]
#label=
#instance=eth0
#interval=10

[network]
#label=
#instance=wlan0
#interval=30

#[ip-address]
#label=
#interval=300

[ssid]
label=
interval=60

[datetime]
label=
interval=1

[weather]
#label=
label=
# instance is your zipcode
instance=60192
interval=1800
