general {
  output_format = "i3bar"
	colors = true
	color_good = "#41A551"
	color_bad = "#BF5357"
	color_degraded = "#EFC334"
	interval = 2
}

order += "battery 1"

battery 1 {
        format = "%status %percentage %remaining %emptytime"
        format_down = "No battery"
        status_chr = "⚡ CHR"
        status_bat = "🔋 BAT"
        status_unk = "? UNK"
        status_full = " FULL"
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 10
}
